SRCS += $(shell find $(SRCDIR)/ 	 -name '*.cpp') 	

SRCS += $(shell find $(SRCDIR)/ 	 -name '*.c') 	

SRCS += $(shell find $(SRCDIR)/ 	 -name '*.S') 	
	
OBJS = $(addsuffix .o,$(basename $(SRCS)))

LINK = 

INCL = 

PREPROC = 
